# Generated by Django 5.0.7 on 2024-07-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rankingavaliacao',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='seguir',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='plano',
            name='permissoes',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='tipo_usuario',
        ),
        migrations.AlterField(
            model_name='filme',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capa/'),
        ),
        migrations.AddConstraint(
            model_name='rankingavaliacao',
            constraint=models.UniqueConstraint(fields=('avaliacao', 'rank'), name='unique_avaliacao_rank'),
        ),
        migrations.AddConstraint(
            model_name='seguir',
            constraint=models.UniqueConstraint(fields=('seguidor', 'seguido'), name='unique_seguidor_seguido'),
        ),
    ]
