# Generated by Django 5.0.7 on 2024-07-18 20:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_rankingavaliacao_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='status_assinatura',
            field=models.ForeignKey(blank=True, default='basic', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.plano'),
        ),
    ]
