# Generated by Django 5.0.7 on 2024-07-19 18:52

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profileuser_status_assinatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.image_move_directory_path),
        ),
    ]
