# Generated by Django 5.0.7 on 2024-09-09 20:53

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_filme_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='default_images/default_profile.webp', null=True, upload_to=app.models.user_directory_path),
        ),
    ]
